[project]
name = "golden-retriever"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=2.21.0",
    "jupyter>=1.1.1",
    "mteb>=1.36.33",
    "pandas>=2.2.3",
    "transformers>=4.50.3",
]
